const GRAVITY = 0.5;
const GROUND_Y = 340;

const MAP_WIDTH = 1600;
const MAP_HEIGHT = 400;

const CANVAS_WIDTH = 800;
const CANVAS_HEIGHT = 400;

export { GRAVITY, GROUND_Y, MAP_WIDTH, MAP_HEIGHT, CANVAS_WIDTH, CANVAS_HEIGHT };
